Bring some goodies from/for omarchy

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -1,3 +1,8 @@
+{{- if eq .chezmoi.os "linux" }}
+# If not running interactively, stop here
+[[ $- != *i* ]] && return
+{{- end }}
+
 # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
 # Initialization code that may require console input (password prompts, [y/n]
 # confirmations, etc.) must go above this block; everything else may go below.
@@ -100,8 +105,8 @@ source $ZSH/oh-my-zsh.sh
 # export LANG=en_US.UTF-8
 
 export EDITOR='nvim'
-export KUBE_EDITOR='nvim'
-export VISUAL='nvim'
+export KUBE_EDITOR="$EDITOR"
+export SUDO_EDITOR="$EDITOR"
 
 # ------------
 # Path changes
@@ -109,6 +114,9 @@ export VISUAL='nvim'
 PATH=$PATH:$(go env GOPATH)/bin
 PATH=$PATH:${HOME}/.local/bin/
 PATH=$PATH:${HOME}/.cargo/bin
+{{- if eq .chezmoi.os "linux" }}
+PATH=$PATH:${HOME}/.local/share/omarchy/bin
+{{- end}}
 
 # ------------
 # Setup config home folder
@@ -141,7 +149,11 @@ export ERL_AFLAGS="-kernel shell_history enabled"
 # ------------
 # Aliases
 # ------------
-alias ls="eza --icons -l"
+alias ls="eza --icons=auto -lh --group-directories-first"
+alias lsa="ls -a"
+alias lt="eza --tree --level=2 --long --icons --git"
+alias lta="lt -a"
+alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
 alias cat="bat --style=auto -P"
 alias less="bat --paging=always"
 alias more="bat --paging=always"
@@ -153,6 +165,11 @@ alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
 alias lg="lazygit"
 alias ld="lazydocker"
 alias cm="chezmoi"
+
+{{- if eq .chezmoi.os "linux" }}
+# Find packages without leaving the terminal
+alias yayf="yay -Slq | fzf --multi --preview 'yay -Sii {1}' --preview-window=down:75% | xargs -ro yay -S"
+{{- end }}
 
 # --------------
 # Set up thefuck (to fix typos)
@@ -209,10 +226,74 @@ export CLAUDE_CODE_ENABLE_UNIFIED_READ_TOOL=true
 # Add Claude Code to path
 export PATH=$PATH:"$HOME/.claude/local"
 
+# --------------
+# Helper functions
+# --------------
+#
 # Helper function to list open ports and their processes
 open_ports() {
   sudo lsof -iTCP -sTCP:LISTEN -n -P
 }
+
+compress() { tar -czf "${1%/}.tar.gz" "${1%/}"; }
+decompress() { "tar -xzf" "${1%/}"; }
+
+{{- if eq .chezmoi.os "linux" }}
+# Helper function to mimic macOS's `open` command on Linux
+open() {
+  xdg-open "$@" >/dev/null 2>&1
+}
+
+web2app() {
+  if [[ $# -ne 3 ]]; then
+    echo "Usage: web2app <AppName> <AppURL> <IconURL> (IconURL must be in PNG -- use https://dashboardicons.com)"
+    return 1
+  fi
+
+  local APP_NAME="$1"
+  local APP_URL="$2"
+  local ICON_URL="$3"
+  local ICON_DIR="$HOME/.local/share/applications/icons"
+  local DESKTOP_FILE="$HOME/.local/share/applications/${APP_NAME}.desktop"
+  local ICON_PATH="${ICON_DIR}/${APP_NAME}.png"
+
+  mkdir -p "$ICON_DIR"
+
+  if ! curl -sL -o "$ICON_PATH" "$ICON_URL"; then
+    echo "Error: Failed to download icon."
+    return 1
+  fi
+
+  cat > "$DESKTOP_FILE" <<EOF
+[Desktop Entry]
+Version=1.0
+Name=$APP_NAME
+Comment=$APP_NAME
+Exec=vivaldi --new-window --ozone-platform=wayland --app="$APP_URL" --name="$APP_NAME" --class="$APP_NAME"
+Terminal=false
+Type=Application
+Icon=$ICON_PATH
+StartupNotify=true
+EOF
+
+  chmod +x "$DESKTOP_FILE"
+}
+
+web2app-remove() {
+  if [[ $# -ne 1 ]]; then
+    echo "Usage: web2app-remove <AppName>"
+    return 1
+  fi
+
+  local APP_NAME="$1"
+  local ICON_DIR="$HOME/.local/share/applications/icons"
+  local DESKTOP_FILE="$HOME/.local/share/applications/${APP_NAME}.desktop"
+  local ICON_PATH="${ICON_DIR}/${APP_NAME}.png"
+
+  [[ -f "$DESKTOP_FILE" ]] && rm "$DESKTOP_FILE"
+  [[ -f "$ICON_PATH" ]] && rm "$ICON_PATH"
+}
+{{- end }}
 
 # BEGIN opam configuration
 # This is useful if you're using opam as it adds:
